<center> </center>

<center><font size=5 face="Helvetica" color=#306998><b>
Manim Kindergarten Tutorials
</b></font></center>

<center><font face="Helvetica" size=2><b>Ang Chen</b></font></center>
<center><font face="Helvetica" size=3>March, 2024</font></center>

***

In this notebook, we will learn how to use Manim to create animations.
And we will break down intto five parts:
1. Position of Objects and Coordinate Transformations
1. Common Geometric Classes
1. Representation, Operations, and Settings of Colors
1. Inserting SVG, Images, and Text
1. Coordinate Systems and Graphics  

Let's get started!
First, let's import the necessary modules. 


# Import the Libraries

In [1]:
from manimlib import *

# Position of Objects and Coordinate Transformations

The coordinate of a point is represented by a np.array([x, y, z]) in Manim:
 * For 3D scenes, it's $\texttt{np.array([x,y,z])}$
 * For 2D scenes, it's $\texttt{np.array([x,y,0])}$ (z-coordinate is set to 0)

In [2]:
ORIGIN, UP, DOWN, LEFT, RIGHT

(array([0., 0., 0.]),
 array([0., 1., 0.]),
 array([ 0., -1.,  0.]),
 array([-1.,  0.,  0.]),
 array([1., 0., 0.]))

In [3]:
UL, UR, DL, DR

(array([-1.,  1.,  0.]),
 array([1., 1., 0.]),
 array([-1., -1.,  0.]),
 array([ 1., -1.,  0.]))

In [4]:
TOP, BOTTOM, LEFT_SIDE, RIGHT_SIDE

(array([0., 4., 0.]),
 array([ 0., -4.,  0.]),
 array([-7.11111111,  0.        ,  0.        ]),
 array([7.11111111, 0.        , 0.        ]))

In [5]:
OUT, IN

(array([0., 0., 1.]), array([ 0.,  0., -1.]))

In [6]:
2*UP + 3*LEFT

array([-3.,  2.,  0.])

# Common Geometric Classes

# Representation, Operations, and Settings of Colors

# Inserting SVG, Images, and Text

# Coordinate Systems and Graphics